### ISSUE TITLE
JavaScript code format single vs double quotes

### ISSUE THREAD

**Issue by 4ndyZ** [OTHRegensburgWebDevKIDS/tutors_course#2]
We are using different styles of quotes in the course examples and labs (even between the same lab).  For consistency we should either single or double quotes.

@mheckner Please propose a quote style.

### TODO:

- [x] Agree on quote style
- [x] Make quotes style consistent

**Comment by mheckner** [comment]
I always use double quotes (if I do not make mistakes), so lets use these. Thanks!
