### ISSUE TITLE
Der/Die/Das View

### ISSUE THREAD

**Issue by 4ndyZ** [OTHRegensburgWebDevKIDS/tutors_course#3]
View is an important noun in the course. In English it is simple "the view". But in German we have "der/die/das".

Throughout the course we use "der View" or "das View" in alternation. For consistency we should choose when of the German articles.

 @mheckner Please decide on an article.

TODO:

- [x] Agree on article
- [x] Make view article consistent

**Comment by mheckner** [comment]
Lets use "der View" - Thanks!
